### ISSUE TITLE
Can't join with b6.1

### ISSUE THREAD

**Issue by hobbes6378** [Elementars/Elementars-b5.2#5]
whenever i join a single player world, after loading, before i get into the world itself, it instantly shuts down the internal server and closes the game (no crash report). whenever i join a multiplayer sever it instantly closes the game as well (no crash report). this problem did not occur when using b5.3 or b5.2 only b6.1.

**Comment by cumsex500** [comment]
same

**Comment by Elementars** [comment]
latest.log can be used if no crash reports are generated

**Comment by hobbes6378** [comment]
I'll see into that

**Comment by hobbes6378** [comment]
for some reason its fixed for now. all i did was delete some text regarding a problem i had with something else. i got rid of any host with "mojang" in it in the text document %SystemRoot%\System32\drivers\etc\hosts. that was a problem with alts and not having any connection. im not fully sure if that was what solved the problem but thats all i did.
