### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by githubUser01234567890** [Elementars/Elementars-b5.2#6]
A few months ago I downloaded elementars 6.1 and ran it through a virustotal, several engines detected a Java Trojan but i just though they were false-positives since the code is obfuscated. I installed 6.1 in my FML and ran minecraft. This worked perfectly fine and was really good although a few days later my computer was quite slow and could barely load any basic applications and i thought it was just caused by some background junk files. I deleted some image/audio files in my downloads folder and restarted my computer. This time, it was even worse - i couldn't even log into my computer and i was forced to wipe my HardDrive disc and re-install the operating system. Then, my computer was working fine. (I also didn't update or install/download any software/files after downloading this) so that's why i think this has a Java trojan in it.

**Comment by Elementars** [comment]
user error
